### ISSUE TITLE
Race condition building messages

### ISSUE THREAD

**Issue by tfoote** [squarerobot/bagger#1]
The message dependencies have not been declared and this is causing a race condition when building the messages. 

It's passing for 32bit http://build.ros.org/view/Kbin_uX32/job/Kbin_uX32__bagger__ubuntu_xenial_i386__binary/

But failing on 64bit systems. 
http://build.ros.org/view/Kbin_uX32/job/Kbin_uX64__bagger__ubuntu_xenial_amd64__binary/

You need to use the `add_dependencies` method in CMake to ensure the message headers are generated before the target is attempted to be built. 

Some good resources; 
https://answers.ros.org/question/73048/first-compile-with-messages-messages-not-found/
https://answers.ros.org/question/192758/messages-not-being-generated-before-dependent-package/
https://answers.ros.org/question/188982/message-headers-wont-build-first/

**Comment by brenden-gibbons** [comment]
Thanks for pointing this out!
