### ISSUE TITLE
Publish bag file name for active profiles

### ISSUE THREAD

**Issue by agdespopoulos** [squarerobot/bagger#2]
Currently, Bagger publishes whether or not a profile is active. However, it does not publish the name of the log being created etc, and this would be good information to have.

**Comment by brenden-gibbons** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bagger publish bag name, release for melodic](https://trello.com/c/ZVFJXqXX/563-bagger-publish-bag-name-release-for-melodic)

**Comment by brenden-gibbons** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bagger - publish current bag name](https://trello.com/c/aCi3FSqy/583-bagger-publish-current-bag-name)

**Comment by brenden-gibbons** [comment]
Closed grossly in e985a3cedf5ad67f16e108c597879633e10206b6
